package kim.biryeong.semiontd.augment;

import java.util.List;
import java.util.Map;
import java.util.Set;

import static kim.biryeong.semiontd.augment.AugmentRarity.*;

/** Approved job cards, including stable Crowdin review IDs and configured description templates. */
final class JobAugmentCatalog {
    record Entry(String reviewId, AugmentDefinition definition, Map<String, Double> parameters) {}

    private static final List<Entry> ENTRIES = List.of(
            card("J01-S", "villager_towers", "s", "유산 상속", SILVER,
                    "라운드에 처음 쓰러진 생존 성장 타워의 영구 스택 {inheritRatio:percent}를 가장 가까운 같은 계열 타워에 임시 상속. 영구·임시 합계 상한은 기본 상한의 {capMultiplier}배.",
                    Map.of("inheritRatio", 0.5, "capMultiplier", 3.0)),
            card("J01-G1", "villager_towers", "g1", "장수 만세", GOLD,
                    "현재 생존 성장 타워의 영구 스택 +{initialStacks}. 매 웨이브 영구 스택만큼 추가 공격을 준비하며 최대 {maxExtraAttacks}회.",
                    Map.of("initialStacks", 3.0, "maxExtraAttacks", 5.0)),
            card("J01-G2", "villager_towers", "g2", "연쇄 폭발", GOLD,
                    "라클 캣의 시체 폭발 반경 +{radiusBonus}블록. 폭발로 처치한 적도 최대 {maxChainDepth}단계까지 연쇄 폭발.",
                    Map.of("radiusBonus", 1.0, "maxChainDepth", 2.0)),
            card("J01-P", "villager_towers", "p", "마을의 거신", PRISMATIC,
                    "지정한 철 골렘의 최대 체력 +{maxHealthBonus:percent}. {intervalTicks:seconds}초마다 반경 {radius}블록의 적 최대 {maxTargets}기에게 최대 체력 {healthDamageRatio:percent}의 물리 피해.",
                    Map.of("maxHealthBonus", 2.0, "intervalTicks", 60.0, "radius", 4.0, "maxTargets", 12.0, "healthDamageRatio", 0.12)),
            card("J02-S", "villager_adv_towers", "s", "멘토 & 멘티", SILVER,
                    "라운드 경험치 지급 시 경험치가 가장 적은 주민 1기가 가장 많은 주민의 정상 지급량의 {experienceRatio:percent}를 추가 경험치로 획득합니다.",
                    Map.of("experienceRatio", 0.5)),
            card("J02-G1", "villager_adv_towers", "g1", "조기 졸업", GOLD,
                    "승급의 경험치 제한을 제거하는 대신 다이아 요구량이 {upgradeCostBonus:percent} 증가합니다. 라운드 경험치 중 티어에 따른 지급량이 {tierExperienceMultiplier}배가 됩니다.",
                    Map.of("upgradeCostBonus", 0.4, "tierExperienceMultiplier", 2.0)),
            card("J02-G2", "villager_adv_towers", "g2", "역할 대항전", GOLD,
                    "서로 다른 주민 계열이 {requiredKinds}종 이상 살아 있으면 {intervalTicks:seconds}초마다 각 계열에서 경험치가 가장 높은 타워 1기가 한 번 추가 행동합니다. 같은 스타터의 승급 분기는 같은 계열입니다.",
                    Map.of("requiredKinds", 3.0, "intervalTicks", 120.0)),
            card("J02-P", "villager_adv_towers", "p", "수석 졸업", PRISMATIC,
                    "웨이브 경험치 지급 뒤 경험치가 가장 높은 공격 타워 1기가 이번 전투 동안 레인 전체를 사거리로 사용합니다. 기본 공격 시 추가 적 {extraTargets}기에게 {damageRatio:percent} 피해로 공격합니다.",
                    Map.of("extraTargets", 2.0, "damageRatio", 0.6)),
            card("J03-S", "undead_towers", "s", "헌혈의 집", SILVER,
                    "언데드 타워가 초과 흡혈한 체력의 {overflowRatio:percent}를 반경 {radius}블록 내 현재 체력이 가장 낮은 아군 타워 1기에 전달합니다.",
                    Map.of("overflowRatio", 0.1, "radius", 4.0)),
            card("J03-G1", "undead_towers", "g1", "뼈가 실린 공격", GOLD,
                    "기존 성장 상한에 도달한 스켈레톤은 성장 범위 안 같은 레인의 적이 {deathsPerCharge}기 죽을 때마다 충전합니다. 유효한 기본 공격마다 충전 1회를 소비해 다른 적 최대 {targetCount}기에게 각각 공격력 {damageRatio:percent}의 추가 물리 공격을 가합니다. 충전은 누적되며 라운드 종료 시 사라집니다.",
                    Map.of("deathsPerCharge", 5.0, "targetCount", 3.0, "damageRatio", 0.5)),
            card("J03-G2", "undead_towers", "g2", "두번째 기회", GOLD,
                    "언데드 타워가 실제로 죽으면 {reviveDelayTicks:seconds}초 뒤 같은 자리에서 최대 체력의 {reviveHealthRatio:percent}로 부활합니다. 부활한 타워의 공격력이 {damageBonus:percent} 증가합니다. 타워마다 라운드당 1회이며 전투 종료 시 부활 대기를 취소합니다.",
                    Map.of("reviveDelayTicks", 20.0, "reviveHealthRatio", 0.6, "damageBonus", 0.6)),
            card("J03-P", "undead_towers", "p", "사령왕", PRISMATIC,
                    "지정한 내 원본 스켈레톤 계열 1기의 공격력과 최대 체력이 {statBonus:percent} 증가합니다. 기존 성장 범위 안 같은 레인의 적이 {deathsPerSummon}기 죽을 때마다 당시 최대 체력과 공격력의 {copyRatio:percent}인 복제본 {copiesPerSummon}기를 생성합니다. 동시 최대 {maxCopies}기이며 원래 전투 능력을 계승하지만 성장·소환·증강 발동은 계승하지 않습니다. 복제본은 슬롯을 쓰지 않고 원본이 전투 중 죽어도 라운드 종료까지 유지되며 원본을 판매하면 제거됩니다.",
                    Map.of("statBonus", 1.0, "deathsPerSummon", 5.0, "copyRatio", 0.35, "copiesPerSummon", 2.0, "maxCopies", 6.0)),
            card("J04-S", "animal_towers", "s", "종을 뛰어넘는 우정", SILVER,
                    "각 동물이 다른 종류의 동물 최대 1기를 같은 종류의 무리로 취급합니다. 가상 무리는 우두머리 승급 조건에 포함하지 않습니다.",
                    Map.of()),
            card("J04-G1", "animal_towers", "g1", "우두머리", GOLD,
                    "우두머리 동물의 최대 체력이 {maxHealthBonus:percent}, 공격력이 {damageBonus:percent} 증가합니다. 기본 공격 시 대상 반경 {radius}블록에 공격력의 {damageRatio:percent} 추가 물리 피해를 입힙니다.",
                    Map.of("maxHealthBonus", 1.0, "damageBonus", 0.6, "radius", 2.5, "damageRatio", 0.6)),
            card("J04-G2", "animal_towers", "g2", "\"무리\" 공격", GOLD,
                    "같은 종류의 동물이 기본 공격을 합계 {everyAttacks}번 적중하면 같은 종류의 다른 동물 최대 {maxAllies}기가 해당 적을 {damageRatio:percent} 피해로 공격합니다. 추가 공격은 증강을 충전하거나 발동하지 않습니다.",
                    Map.of("everyAttacks", 5.0, "maxAllies", 3.0, "damageRatio", 1.0)),
            card("J04-P", "animal_towers", "p", "우두머리 연합", PRISMATIC,
                    "서로 다른 우두머리 {requiredLeaderKinds}종이 살아 있으면 모든 동물이 우두머리의 강화 효과를 {auraMultiplier}배로 공유합니다. 공유 효과는 종, 최대 무리, 거리 제한을 무시합니다.",
                    Map.of("requiredLeaderKinds", 3.0, "auraMultiplier", 2.0)),
            card("J05-S", "warlock_towers", "s", "유언", SILVER,
                    "제물을 흡수하면 제물이 있던 곳에서 가장 가까운 적 1기에게 제물 공격력의 {damageRatio:percent} 피해를 줍니다. 제물의 원래 공격 유형을 사용합니다.",
                    Map.of("damageRatio", 3.0)),
            card("J05-G1", "warlock_towers", "g1", "폭발형 제물", GOLD,
                    "흡수한 제물이 반경 {radius}블록으로 폭발해 최대 {maxTargets}기의 적에게 제물 최대 체력의 {healthRatio:percent} 마법 피해를 줍니다. 흡수로 얻는 영구 성장량이 {growthBonus:percent} 증가합니다.",
                    Map.of("radius", 3.0, "maxTargets", 12.0, "healthRatio", 1.0, "growthBonus", 0.25)),
            card("J05-G2", "warlock_towers", "g2", "(진)각성", GOLD,
                    "각성을 즉시 해금합니다. 다른 아군이 살아있어도 체력 {healthThreshold:percent} 이하에서 각성하며, 각성 중 주는 피해가 {damageBonus:percent} 증가합니다.",
                    Map.of("healthThreshold", 0.6, "damageBonus", 0.2)),
            card("J05-P", "warlock_towers", "p", "악마의 동업", PRISMATIC,
                    "흑마법사 핵심을 최대 2기 보유할 수 있으며 두 번째 핵심은 {secondCoreCost}다이아로 설치합니다. 제물 흡수로 얻은 성장과 회복을 다른 생존한 흑마법사 핵심도 받습니다. 공유는 흡수 횟수·유언·폭발을 다시 발동하지 않으며, 다른 흑마법사 핵심이 살아있어도 각성할 수 있습니다.",
                    Map.of("secondCoreCost", 700.0)),
            card("J06-S", "legion_towers", "s", "트릭 쇼", SILVER,
                    "원본마다 라운드에 한 번, 치명적인 피해를 무효화하고 자신의 복제본을 소모해 피격 전 체력에 최대 체력의 {healRatio:percent}를 회복합니다. 최대 체력을 넘지 않습니다.",
                    Map.of("healRatio", 0.3)),
            card("J06-G1", "legion_towers", "g1", "파워레인저", GOLD,
                    "내 레인의 같은 종류·같은 티어 복제본을 합쳐 최대 체력, 현재 체력과 공격력을 각각 합산합니다. 재료마다 크기가 {scalePerClone:percent} 증가하고 원본과 독립적으로 행동하며, 공격 시 반경 {radius}블록의 모든 적에게 {damageRatio:percent}의 추가 범위 피해를 줍니다.",
                    Map.of("scalePerClone", 0.05, "radius", 2.0, "damageRatio", 0.25)),
            card("J06-G2", "legion_towers", "g2", "카리스마", GOLD,
                    "본체가 기본 공격을 {attacks}회 적중할 때마다 해당 본체의 모든 복제본의 다음 기본 공격이 {damageRatio:percent}의 피해를 줍니다.",
                    Map.of("attacks", 5.0, "damageRatio", 3.0)),
            card("J06-P", "legion_towers", "p", "복제 공장", PRISMATIC,
                    "웨이브 시작에 실제 투자액이 가장 높은 본체의 복제본이 첫 공격마다 다음 세대 복제본을 생성합니다. 최초 복제본부터 최대 {maxGeneration}세대이며 마지막 세대는 증식하지 않습니다. 자식은 부모 최대 체력과 공격력의 {childRatio:percent}를 가지며 만료 시점이 같습니다. 플레이어당 라운드 추가 복제본은 예약을 포함해 최대 {maxAdditional}기입니다. 합체 후에도 재료별 증식 권리를 보존합니다.",
                    Map.of("maxGeneration", 3.0, "childRatio", 0.8, "maxAdditional", 12.0)),
            card("J07-S", "resonance_towers", "s", "인터넷 친구", SILVER,
                    "웨이브 시작 시 공명 수가 가장 적은 무블룸 1기가 아직 연결하지 않은 다른 종 중 공명 수가 가장 높은 타워와 추가 연결합니다. 동률이면 가장 가까운 타워를 고르며 공명 수가 1 증가합니다. 후보가 없으면 추가하지 않습니다.",
                    Map.of()),
            card("J07-G1", "resonance_towers", "g1", "원격 연결", GOLD,
                    "무블룸의 공명 연결 범위가 {linkRange}블록이 됩니다. 공명 수가 {requiredLinks} 이상이면 공격력이 {damageBonus:percent}, 최대 체력이 {maxHealthBonus:percent} 증가합니다.",
                    Map.of("linkRange", 3.0, "requiredLinks", 3.0, "damageBonus", 0.5, "maxHealthBonus", 0.5)),
            card("J07-G2", "resonance_towers", "g2", "화음", GOLD,
                    "현재 티어의 최대 공명 단계인 타워가 기본 공격을 {everyAttacks}번 적중할 때마다 대상 반경 {radius}블록의 적 최대 {maxTargets}기에게 공격력의 {damageRatio:percent} 추가 마법 피해를 입힙니다.",
                    Map.of("everyAttacks", 3.0, "radius", 3.0, "maxTargets", 12.0, "damageRatio", 2.0)),
            card("J07-P", "resonance_towers", "p", "공명 순환", PRISMATIC,
                    "웨이브 시작 후 {intervalTicks:seconds}초마다 공명 단계가 가장 높은 무블룸 최대 {maxTowers}기가 기존 사거리의 적을 즉시 공격합니다. 추가 공격은 증강을 충전하거나 발동하지 않습니다.",
                    Map.of("intervalTicks", 120.0, "maxTowers", 5.0)),
            card("J08-S", "illager_towers", "s", "흉조", SILVER,
                    "우민 타워마다 라운드 첫 기본 공격 적중 후 {markDurationTicks:seconds}초 표식. 내 우민에게 받는 피해 +{markDamageBonus:percent}. 기존 표식에 합산.",
                    Map.of("markDurationTicks", 80.0, "markDamageBonus", 0.2)),
            card("J08-G1", "illager_towers", "g1", "매복", GOLD,
                    "웨이브 시작 시 즉시 습격이 발동합니다. 시작 후 {durationTicks:seconds}초간 내 우민 타워의 공격속도가 {attackSpeedBonus:percent} 증가합니다.",
                    Map.of("attackSpeedBonus", 0.3, "durationTicks", 160.0)),
            card("J08-G2", "illager_towers", "g2", "다음은 너야", GOLD,
                    "내 원본 타워가 내 표식 또는 흉조가 새겨진 적을 처치하면 반경 {radius}블록 내 최대 {targetCount}기의 적에게 원래 지속시간 전체로 표식을 전이하고, 처치한 타워 공격력의 {damageRatio:percent}만큼 추가 마법 피해를 줍니다. 공통 증강 타워도 발동하며 같은 표식은 중첩하지 않고 지속시간을 갱신합니다.",
                    Map.of("radius", 3.0, "targetCount", 3.0, "damageRatio", 1.5)),
            card("J08-P", "illager_towers", "p", "대습격", PRISMATIC,
                    "습격 중에도 기존 조건으로 추가 습격 게이지를 얻습니다. 추가 게이지 {gaugePerVolley}마다 공격 중인 내 우민 타워들이 현재 공격 중인 적에게 공격력의 {damageRatio:percent}로 추가 물리 공격을 가합니다. 추가 공격은 증강을 다시 충전하거나 발동하지 않습니다.",
                    Map.of("gaugePerVolley", 50.0, "damageRatio", 3.0)),
            card("J09-S", "nether", "s", "방혈", SILVER,
                    "네더 타워가 자연 감소로 실제 잃은 체력이 최대 체력의 {healthRatio:percent}에 도달할 때마다 충전합니다. 유효한 기본 공격마다 충전 1회를 소비해 그만큼 추가 마법 피해를 줍니다. 충전은 누적되며 라운드 종료 시 사라집니다.",
                    Map.of("healthRatio", 0.2)),
            card("J09-G1", "nether", "g1", "다혈질", GOLD,
                    "네더 타워의 체력 35% 이하 추가 효과가 체력 {healthThreshold:percent} 이하부터 발동합니다. 자연 체력 감소량이 {decayReduction:percent} 줄어듭니다.",
                    Map.of("healthThreshold", 0.6, "decayReduction", 0.5)),
            card("J09-G2", "nether", "g2", "2 페이즈", GOLD,
                    "네더 타워가 좀비 상태로 전환하면 {durationTicks:seconds}초간 체력이 1 미만으로 내려가지 않습니다. 이 동안 기본 공격이 대상 주변 반경 {radius}블록에 공격력 {damageRatio:percent}의 추가 물리 피해를 줍니다.",
                    Map.of("durationTicks", 60.0, "radius", 3.0, "damageRatio", 0.5)),
            card("J09-P", "nether", "p", "불사의 토템", PRISMATIC,
                    "네더 타워가 좀비 상태에서 실제로 죽으면 {reviveDelayTicks:seconds}초 뒤 같은 자리에서 최대 체력의 {reviveHealthRatio:percent}로 한 번 더 부활합니다. 부활 후 주는 피해가 {damageBonus:percent} 증가합니다. 타워마다 라운드당 1회이며 전투 종료 시 부활 대기를 취소합니다.",
                    Map.of("reviveDelayTicks", 20.0, "reviveHealthRatio", 0.5, "damageBonus", 1.0)),
            card("J10-S", "end_towers", "s", "공허 지뢰", SILVER,
                    "힘 전달을 완료한 타워 자리에 공허 지뢰를 만듭니다. 적이 접근하면 반경 {radius}블록의 최대 {maxTargets}기에게 전달 전 타워 최대 체력의 {healthRatio:percent} 마법 피해를 줍니다.",
                    Map.of("radius", 3.0, "maxTargets", 8.0, "healthRatio", 1.0)),
            card("J10-G1", "end_towers", "g1", "폭풍 성장", GOLD,
                    "힘 전달 시간이 기존의 {durationMultiplier:percent}가 됩니다. 전투마다 전달을 완료한 타워 {transfersPerCharge}기당 다음 기본 공격의 주 대상과 기존 보조 대상에게 공격력의 {damageRatio:percent} 추가 마법 피해를 줍니다. 충전은 최대 1회 보관합니다.",
                    Map.of("durationMultiplier", 0.5, "transfersPerCharge", 3.0, "damageRatio", 1.5)),
            card("J10-G2", "end_towers", "g2", "삼중 브레스", GOLD,
                    "엔더 드래곤이 {intervalTicks:seconds}초마다 {burstIntervalTicks}틱 간격으로 브레스를 {shots}번 발사합니다. 각 브레스는 길이 {length}블록, 폭 {width}블록이며 최대 {maxTargets}기에게 공격력의 {damageRatio:percent} 마법 피해를 줍니다. 표적이 유효하지 않으면 기존 사거리에서 다시 고릅니다.",
                    Map.of("intervalTicks", 120.0, "burstIntervalTicks", 4.0, "shots", 2.0, "length", 12.0, "width", 3.0, "maxTargets", 12.0, "damageRatio", 0.75)),
            card("J10-P", "end_towers", "p", "쌍둥이 용", PRISMATIC,
                    "매 웨이브 부화 직후 당시 형태의 복제본 1기를 만듭니다. 생성 당시 본체 최대 체력과 공격력의 {statRatio:percent}를 고정하고 원래 전투 능력을 계승합니다. 성장·추가 소환·증강은 계승하지 않습니다. 일반 슬롯을 쓰지 않고 판매·승급할 수 없으며, 본체가 전투 중 죽어도 라운드 종료까지 남습니다. 본체를 판매·영구 제거하면 함께 사라집니다.",
                    Map.of("statRatio", 0.5)),
            card("J11-S", "ocean", "s", "물 돌려쓰기", SILVER,
                    "소프트캡에 도달한 바다 타워가 받을 물을 같은 공급원에 연결된 물이 가장 적은 타워에게 돌려줍니다. 물량 감쇠 전 배분량을 옮기며 공급원 중복 감쇠는 한 번 적용합니다.",
                    Map.of()),
            card("J11-G1", "ocean", "g1", "만조", GOLD,
                    "물 타워의 공급량과 바다 타워의 물 소프트캡이 {supplyMultiplier}배가 됩니다. 공급 중단 한도는 유지합니다. 웨이브 시작 시 물을 사용하는 내 바다 타워의 물을 최소 {openingWater}로 맞춥니다.",
                    Map.of("supplyMultiplier", 1.5, "openingWater", 150.0)),
            card("J11-G2", "ocean", "g2", "거센 해류", GOLD,
                    "바다 공격 타워가 실제 물을 {waterPerCharge} 소모할 때마다 해류를 충전합니다. 다음 유효한 기본 공격마다 충전 1회를 소비해 대상 반경 {radius}블록의 적 최대 {targets}기에게 공격력 {damageRatio:percent}의 마법 피해를 줍니다. 충전은 누적되며 라운드 종료 시 사라집니다.",
                    Map.of("waterPerCharge", 30.0, "radius", 3.0, "targets", 12.0, "damageRatio", 2.0)),
            card("J11-P", "ocean", "p", "밀물", PRISMATIC,
                    "전투 시작 {periodTicks:seconds}초부터 {periodTicks:seconds}초마다 {durationTicks:seconds}초 동안 물을 사용하는 내 바다 타워의 물을 소프트캡 이상으로 유지합니다. 이미 소프트캡을 넘은 물은 줄이지 않습니다.",
                    Map.of("periodTicks", 240.0, "durationTicks", 80.0)),
            card("J12-S", "ancient_city", "s", "감지 공유", SILVER,
                    "내 스컬크 위의 적에게 감지 표식을 붙이면 반경 {radius}블록의 표식 없는 적 최대 {targets}기에도 같은 표식을 전체 지속시간으로 부여합니다. 같은 표식의 효과는 중첩하지 않습니다.",
                    Map.of("radius", 3.0, "targets", 2.0)),
            card("J12-G1", "ancient_city", "g1", "영역 전개", GOLD,
                    "내 스컬크 위의 고대 도시 타워는 내 스컬크 위의 적을 사거리 밖에서도 공격합니다. 기존 적 레인 제한은 유지합니다.",
                    Map.of()),
            card("J12-G2", "ancient_city", "g2", "연쇄 소닉 붐", GOLD,
                    "워든의 소닉 붐 대상이 {extraTargets}기 증가합니다. 보조 대상도 주 대상의 {secondaryRatio:percent} 피해와 감지 표식의 피해 증가 효과를 받습니다.",
                    Map.of("extraTargets", 3.0, "secondaryRatio", 1.0)),
            card("J12-P", "ancient_city", "p", "깨어난 도시", PRISMATIC,
                    "감지 표식이 있는 적 아래의 내 스컬크 최대 {centers}곳에서 충격파를 발사합니다. 각 충격파는 반경 {radius}블록의 적 최대 {targets}기에게 가장 강한 내 워든의 소닉 붐 주 대상 피해 {damageRatio:percent}를 줍니다. 재사용 대기시간은 {cooldownTicks:seconds}초입니다.",
                    Map.of("centers", 6.0, "radius", 2.0, "targets", 8.0, "damageRatio", 2.0, "cooldownTicks", 160.0)),
            card("J13-S", "hero_party", "s", "합동 공격", SILVER,
                    "용사의 기본 공격이 {everyAttacks}번 적중할 때마다 동료 1기가 즉시 기본 공격합니다. 배치 순서대로 순환하며 쓰러진 동료는 건너뜁니다.",
                    Map.of("everyAttacks", 3.0)),
            card("J13-G1", "hero_party", "g1", "주인공 버프", GOLD,
                    "장착 무기의 1·3·5강 고유 효과를 즉시 해금합니다. 실제 5강부터 피해·회복·버프·디버프의 세기와 체력 비례 피해 상한이 {effectMultiplier}배가 됩니다. 범위·대상 수·지속시간·주기·체력 발동 조건·강화 가격은 유지합니다.",
                    Map.of("effectMultiplier", 1.5)),
            card("J13-G2", "hero_party", "g2", "합동 공격", GOLD,
                    "동료 {companions}명이 생존하면 용사의 매 {everyAttacks}번째 기본 공격 적중 시 대상 반경 {radius}블록의 적 최대 {maxTargets}기에게 용사와 동료 공격력 합계의 {damageRatio:percent} 마법 피해를 줍니다.",
                    Map.of("companions", 4.0, "everyAttacks", 5.0, "radius", 4.0, "maxTargets", 12.0, "damageRatio", 3.0)),
            card("J13-P", "hero_party", "p", "전설의 용사", PRISMATIC,
                    "용사의 무기 공격력 +{weaponDamageBonus:percent}, 최대 체력 +{healthBonus:percent}. 매 {everyAttacks}번째 기본 공격 적중 시 길이 {length}블록·폭 {width}블록의 적 최대 {maxTargets}기에게 공격력의 {damageRatio:percent} 물리 피해를 줍니다.",
                    Map.of("weaponDamageBonus", 2.0, "healthBonus", 1.5, "everyAttacks", 3.0, "length", 12.0, "width", 3.0, "maxTargets", 12.0, "damageRatio", 5.0)),
            card("J14-S", "succubus", "s", "고약한 잠버릇", SILVER,
                    "잠든 아군 공격 타워가 {intervalTicks:seconds}초마다 공격력의 {damageRatio:percent}로 기본 공격합니다.",
                    Map.of("intervalTicks", 40.0, "damageRatio", 0.6)),
            card("J14-G1", "succubus", "g1", "루시드 드림", GOLD,
                    "아군이 꿈 스택으로 잠들지 않으며, 꿈 스택의 공격력과 공격속도 증가량이 {dreamBonus:percent} 증가합니다.",
                    Map.of("dreamBonus", 0.5)),
            card("J14-G2", "succubus", "g2", "악몽 전염", GOLD,
                    "잠든 적이 죽으면 반경 {radius}블록의 다른 적 최대 {maxTargets}기가 {durationTicks:seconds}초 동안 잠듭니다. 전염은 최대 {maxDepth}단계까지 이어집니다.",
                    Map.of("radius", 3.0, "maxTargets", 2.0, "durationTicks", 40.0, "maxDepth", 2.0)),
            card("J14-P", "succubus", "p", "몽유병", PRISMATIC,
                    "잠든 적 최대 {maxTargets}기가 {intervalTicks:seconds}초마다 가장 가까운 다른 적에게 자신의 공격력 {damageRatio:percent}만큼 마법 피해를 줍니다. 기절 중에는 발동하지 않습니다.",
                    Map.of("maxTargets", 3.0, "intervalTicks", 20.0, "damageRatio", 1.5)),
            card("J15-S", "adversary_towers", "s", "다크 히어로", SILVER,
                    "여우 외의 내 타워가 내 대적자를 처치하면 처치 위치 반경 {radius}블록의 적에게 대적자 최대 체력의 {healthRatio:percent} 마법 피해를 줍니다.",
                    Map.of("radius", 3.0, "healthRatio", 0.25)),
            card("J15-G1", "adversary_towers", "g1", "라이벌 매치", GOLD,
                    "여우가 자기 라이벌을 처치해 얻는 전직 점수 {scoreMultiplier}배. 최대 체력 {healRatio:percent} 추가 회복, {durationTicks:seconds}초간 공격력 +{damageBonus:percent}.",
                    Map.of("scoreMultiplier", 2.0, "healRatio", 0.3, "damageBonus", 1.0, "durationTicks", 120.0)),
            card("J15-G2", "adversary_towers", "g2", "적응", GOLD,
                    "여우가 내 라이벌을 처치하면 전투 동안 라이벌 최대 체력의 {healthRatio:percent}, 공격력의 {damageRatio:percent}를 흡수합니다. 흡수 상한은 여우의 전투 시작 최대 체력 {healthCapRatio:percent}, 공격력 {damageCapRatio:percent}이며 라운드 종료 시 제거됩니다.",
                    Map.of("healthRatio", 0.2, "damageRatio", 0.5, "healthCapRatio", 1.0, "damageCapRatio", 1.5)),
            card("J15-P", "adversary_towers", "p", "최종장", PRISMATIC,
                    "최종 전직 여우의 공격력 +{damageBonus:percent}, 최대 체력 +{healthBonus:percent}. 라이벌을 처치한 여우는 {durationTicks:seconds}초간 기본 공격의 보조 대상이 {extraTargets}기 늘고 추가 보조 대상에게 {secondaryRatio:percent} 피해를 줍니다.",
                    Map.of("damageBonus", 1.2, "healthBonus", 1.0, "durationTicks", 200.0, "extraTargets", 2.0, "secondaryRatio", 1.0)),
            card("J16-S", "engineer_towers", "s", "관통 탄환", SILVER,
                    "디스펜서 공격이 표적 뒤의 적 최대 {extraTargets}기를 관통해 같은 피해를 줍니다.",
                    Map.of("extraTargets", 1.0)),
            card("J16-G1", "engineer_towers", "g1", "무한 회로", GOLD,
                    "발사기의 신호 1회당 작동 시간이 {activeTicks:seconds}초가 됩니다. 매 사격이 {shotSpacingTicks}틱 간격의 3점사로 바뀌며 두 번째와 세 번째 탄환은 각각 {followupRatio:percent} 피해를 줍니다. 표적이 죽거나 사거리를 벗어나면 기존 사거리 안에서 다시 고릅니다.",
                    Map.of("activeTicks", 120.0, "shotSpacingTicks", 4.0, "followupRatio", 0.5)),
            card("J16-G2", "engineer_towers", "g2", "폭발은 예술이다!", GOLD,
                    "TNT 폭발 {delayTicks:seconds}초 뒤 같은 위치에서 한 번 더 폭발. 두 번째 폭발 피해는 첫 폭발의 {repeatDamageRatio:percent}.",
                    Map.of("delayTicks", 40.0, "repeatDamageRatio", 0.8)),
            card("J16-P", "engineer_towers", "p", "전자동 공장", PRISMATIC,
                    "발판에 연결된 타워가 {intervalTicks:seconds}초마다 자동으로 작동하며, 기술자 타워가 주는 피해가 {damageBonus:percent} 증가합니다. 자동 작동은 발판 사용 횟수와 영구 성장을 올리지 않고 TNT의 라운드당 사용 제한을 유지합니다.",
                    Map.of("intervalTicks", 120.0, "damageBonus", 1.0)),
            card("J17-S", "queen_towers", "s", "땅울림", SILVER,
                    "자이언트가 적을 처형하면, 해당 적의 축소량 {transferRatio:percent}를 {radius}블록 내 적 하나에 전달합니다.",
                    Map.of("transferRatio", 0.5, "radius", 3.0)),
            card("J17-G1", "queen_towers", "g1", "근위대", GOLD,
                    "붉은 여왕 타워 {radius}블록 내 카드병정의 공격속도가 {attackSpeedBonus:percent} 증가합니다.",
                    Map.of("radius", 5.0, "attackSpeedBonus", 0.5)),
            card("J17-G2", "queen_towers", "g2", "궁정 광대", GOLD,
                    "일반 타워 슬롯을 사용하는 무료 조커 {tickets}기 배치권을 받습니다. 조커는 최적 족보의 카드로 계산되고 해당 문양의 능력을 얻습니다. 조커가 포함된 줄의 카드병정 공격속도 +{attackSpeedBonus:percent}. 줄마다 한 번 적용하며 판매 환급과 승급은 없습니다.",
                    Map.of("tickets", 3.0, "attackSpeedBonus", 0.4)),
            card("J17-P", "queen_towers", "p", "왕실 부메랑", PRISMATIC,
                    "자이언트가 처음 경로 끝에 도달하면 되돌아옵니다. 왕복 각 구간에서 적마다 한 번 접촉하며, 귀환 때 처형 조건을 다시 확인합니다.",
                    Map.of()),
            card("J18-S", "atlantis_towers", "s", "쓰나미", SILVER,
                    "거북이가 {intervalTicks:seconds}초마다 자신의 고압 구역 가장자리 적 한 기를 중심 쪽으로 최대 {distance}블록 끌어당깁니다.",
                    Map.of("intervalTicks", 120.0, "distance", 2.0)),
            card("J18-G1", "atlantis_towers", "g1", "심해 압력", GOLD,
                    "돌고래의 기본 공격이 대상 반경 {radius}블록의 다른 적 최대 {targets}기에도 압력 {stacks}스택을 추가합니다. 수압 피해 상한이 공격력의 {damageCap}배가 됩니다.",
                    Map.of("radius", 3.0, "targets", 2.0, "stacks", 1.0, "damageCap", 4.0)),
            card("J18-G2", "atlantis_towers", "g2", "압도적인 존재", GOLD,
                    "거북이가 죽으면 자신의 고압 구역 안 적 최대 {targets}기의 압력을 가득 채우고 즉시 폭발시킵니다.",
                    Map.of("targets", 12.0)),
            card("J18-P", "atlantis_towers", "p", "연쇄 폭발", PRISMATIC,
                    "수압 폭발이 반경 {radius}블록의 다른 적 최대 {targets}기에 폭발 직전 압력의 {transferRatio:percent}를 전달합니다. 고압 구역에서 압력이 가득 찬 적은 즉시 폭발합니다. 한 연쇄에서 최대 {chainTargets}기만 폭발합니다.",
                    Map.of("radius", 3.0, "targets", 2.0, "transferRatio", 0.5, "chainTargets", 12.0)),
            card("J19-S", "plant_towers", "s", "파고드는 줄기", SILVER,
                    "내 토양에 처음 들어온 적을 {stunTicks:seconds}초간 기절시킵니다. 적마다 라운드 한 번만 적용합니다.",
                    Map.of("stunTicks", 20.0)),
            card("J19-G1", "plant_towers", "g1", "급속 개화", GOLD,
                    "내 잔디·회백토에 있는 식물 타워에 즉시 성장 {growthRounds}라운드를 추가합니다. 이후 새 식물은 같은 계열에서 가장 높은 성장 스택의 {inheritRatio:percent}를 내림해 계승하며 기존 성장 효과 상한을 유지합니다.",
                    Map.of("growthRounds", 5.0, "inheritRatio", 0.25)),
            card("J19-G2", "plant_towers", "g2", "포자 증식", GOLD,
                    "버섯이 한 라운드에 최대 {explosions}번 폭발합니다. 폭발 {rearmTicks:seconds}초 뒤 다시 무장하며, 다시 적이 밟아야 점화됩니다. 후속 폭발은 첫 폭발 피해의 {repeatDamageRatio:percent}입니다.",
                    Map.of("explosions", 3.0, "rearmTicks", 60.0, "repeatDamageRatio", 0.8)),
            card("J19-P", "plant_towers", "p", "세계수", PRISMATIC,
                    "지정 도구로 내 지형 타워 한 기를 세계수로 지정합니다. 반경 {radius}블록에서는 토양 종류와 관계없이 식물을 심고 각 계열의 토양 효과를 받습니다. 범위 안 식물의 공격력과 최대 체력 +{statBonus:percent}.",
                    Map.of("radius", 8.0, "statBonus", 0.8)),
            card("J20-S", "army", "s", "특별진급", SILVER,
                    "계급이 있는 군대 타워가 한 라운드에 웨이브 적을 {killsRequired}기 처치하면 즉시 한 계급 진급합니다. 타워마다 라운드당 1회 발동합니다.",
                    Map.of("killsRequired", 3.0)),
            card("J20-G1", "army", "g1", "말년짬", GOLD,
                    "최종 계급 군대 타워의 지휘 범위 안에서 같은 종류 후임이 합계 {attacksRequired}회 공격할 때마다 세 번째 표적에게 지원 사격합니다. 사격한 말년병의 계급 페널티 전 공격력 {damageRatio:percent}를 원래 공격 유형으로 가합니다.",
                    Map.of("attacksRequired", 3.0, "damageRatio", 1.5)),
            card("J20-G2", "army", "g2", "군적금", GOLD,
                    "군대 타워 전역 시 다음 진급 가능한 전투병 스타터를 무료로 설치하는 배치권을 얻습니다. 무료 신병은 즉시 한 계급 진급합니다. 라운드당 1회 획득하며 최대 1장 보관합니다. 시설과 증강 타워는 제외합니다.",
                    Map.of()),
            card("J20-P", "army", "p", "예비군 1년차", PRISMATIC,
                    "웨이브 시작 시 최근 전역한 군대 타워 2기가 예비군으로 재합류합니다. 전역 당시 최대 체력 {healthRatio:percent}, 계급 페널티 전 공격력 {damageRatio:percent}를 가지며 공격 능력만 계승합니다. 일반 슬롯을 쓰지 않고 라운드 종료까지 유지하며 계급 오라, 진급, 전역과 전역 보상이 없습니다.",
                    Map.of("healthRatio", 1.0, "damageRatio", 1.5)),
            card("J21-S", "thunder", "s", "축전지", SILVER,
                    "전력이 부족하지 않고 사거리 안에 적이 없으면 람쥐가 {chargeTicks:seconds}초마다 추가 탄 1발을 준비합니다. 최대 {maxShots}발이며 다음 기본 공격에 각 {damageRatio:percent} 피해로 함께 발사합니다.",
                    Map.of("chargeTicks", 20.0, "maxShots", 3.0, "damageRatio", 1.0)),
            card("J21-G1", "thunder", "g1", "도토리 발전소", GOLD,
                    "피뢰침의 발전량이 {generationBonus:percent} 증가하며 전투 중 파괴되어도 계속 발전합니다. 판매하면 발전이 중단됩니다.",
                    Map.of("generationBonus", 1.0)),
            card("J21-G2", "thunder", "g2", "람쥐 썬더", GOLD,
                    "뇌신 람쥐썬더의 번개가 추가로 {extraTargets}기의 적에게 전이되며, 전이 피해가 {damageRatio:percent}가 됩니다.",
                    Map.of("extraTargets", 3.0, "damageRatio", 1.0)),
            card("J21-P", "thunder", "p", "생체 중계기", PRISMATIC,
                    "람쥐의 번개가 다른 아군 람쥐 최대 {maxRelays}기를 경유합니다. 각 중계 타워의 기존 사거리 안에서 새로운 적 최대 {targetsPerRelay}기에게 {damageRatio:percent} 피해를 주며 같은 적을 중복 공격하지 않습니다.",
                    Map.of("maxRelays", 2.0, "targetsPerRelay", 5.0, "damageRatio", 1.0)),
            card("J22-S", "demon_lord_towers", "s", "마무리 동작", SILVER,
                    "공격 스킬 적중 후 {windowTicks:seconds}초 안의 첫 기본 공격이 공격력 {damageRatio:percent}의 추가 물리 피해를 줍니다.",
                    Map.of("windowTicks", 40.0, "damageRatio", 2.0)),
            card("J22-G1", "demon_lord_towers", "g1", "2페이즈", GOLD,
                    "체력이 처음 {healthThreshold:percent} 이하가 되면 최대 체력의 {healRatio:percent}를 회복하고 모든 스킬의 재사용 대기시간을 초기화하며, {durationTicks:seconds}초간 주는 피해가 {damageBonus:percent} 증가합니다. 라운드당 1회.",
                    Map.of("healthThreshold", 0.3, "healRatio", 0.5, "durationTicks", 200.0, "damageBonus", 0.8)),
            card("J22-G2", "demon_lord_towers", "g2", "왐보콤보", GOLD,
                    "{windowTicks:seconds}초 안에 서로 다른 공격 스킬 {distinctSkills}종을 적중시키면 모든 공격 스킬의 남은 재사용 대기시간이 {cooldownReductionTicks:seconds}초 감소합니다. 이후 {durationTicks:seconds}초간 스킬 피해가 {damageBonus:percent} 증가합니다. 재사용 대기시간 {cooldownTicks:seconds}초.",
                    Map.of("windowTicks", 160.0, "distinctSkills", 3.0, "cooldownReductionTicks", 80.0, "durationTicks", 120.0, "damageBonus", 0.6, "cooldownTicks", 160.0)),
            card("J22-P", "demon_lord_towers", "p", "두 개의 왕좌", PRISMATIC,
                    "{windowTicks:seconds}초 안에 서로 다른 공격 스킬 2종을 적중시키면 공격받지 않는 연출용 분신 2기가 각 스킬의 피해를 {damageRatio:percent}로 한 번씩 재현하고 사라집니다. 추가 비용과 스킬 재사용 대기시간, 증강 재발동이 없습니다. 재사용 대기시간 {cooldownTicks:seconds}초.",
                    Map.of("windowTicks", 160.0, "damageRatio", 1.5, "cooldownTicks", 200.0)),
            card("J23-S", "gamble", "s", "도박 보험", SILVER,
                    "지원 주사위가 1이나 2면 반대편 눈 6이나 5의 전투 효과를 {oppositeEffectRatio:percent}로 추가 적용합니다. 반대편 눈의 다이아 보상은 지급하지 않습니다.",
                    Map.of("oppositeEffectRatio", 0.5)),
            card("J23-G1", "gamble", "g1", "쌍 주사위", GOLD,
                    "주사위 타워와 구경꾼이 주사위를 두 번 굴려 높은 쪽만 사용합니다.",
                    Map.of()),
            card("J23-G2", "gamble", "g2", "바닥의 왕", GOLD,
                    "도박 실패 시 점수 손실 {failureScoreMultiplier}배. {statReversalChance:percent} 확률로 능력치 감소가 같은 양의 증가로 바뀝니다.",
                    Map.of("failureScoreMultiplier", 2.0, "statReversalChance", 0.2)),
            card("J23-P", "gamble", "p", "끝장을 보자", PRISMATIC,
                    "도박 1회 구매로 성공할 때까지 최대 {maxAttempts}회 시도하며 시도마다 점수와 능력치를 정산합니다. 성공 시 다음 기본 공격에 공격력 {jackpotDamageRatio:percent}의 잭팟 폭발을 준비합니다. 반경 {jackpotRadius}블록, 최대 {maxTargets}기, 최대 {maxCharges}회 저장하며 도박사의 원래 공격 유형을 사용합니다. 전부 실패하면 점수 추가 -{allFailedScoreLoss}.",
                    Map.of("maxAttempts", 3.0, "jackpotDamageRatio", 6.0, "jackpotRadius", 3.0, "maxTargets", 12.0, "maxCharges", 3.0, "allFailedScoreLoss", 3.0)),
            card("J24-S", "body", "s", "시선강탈", SILVER,
                    "눈 타워의 빔이 기존 사거리 안에서 가장 가까운 적을 향합니다.",
                    Map.of()),
            card("J24-G1", "body", "g1", "두근두근", GOLD,
                    "심장이 정상적으로 {normalBeats}번 뛸 때마다 추가로 한 번 박동합니다. 추가 박동에도 다른 신체가 함께 행동하며 추가 박동은 이 효과를 재발동하지 않습니다.",
                    Map.of("normalBeats", 2.0)),
            card("J24-G2", "body", "g2", "아드레날린", GOLD,
                    "심장의 최대 체력이 {healthBonus:percent} 증가합니다. 체력이 처음 {healthThreshold:percent} 이하가 되면 최대 체력의 {healRatio:percent}를 회복하고 다음 {fastBeats}번의 박동 간격이 {intervalRatio:percent}가 됩니다. 라운드당 1회.",
                    Map.of("healthBonus", 0.8, "healthThreshold", 0.5, "healRatio", 0.3, "fastBeats", 8.0, "intervalRatio", 0.5)),
            card("J24-P", "body", "p", "예민한 피부", PRISMATIC,
                    "각 피부가 적에게 실제로 잃은 체력을 누적해 현재 최대 체력의 {healthLossRatio:percent}마다 연결된 심장이 추가 박동합니다. 심장마다 {cooldownTicks:seconds}초에 최대 1회이며 대기 박동을 저장하지 않습니다. 누적 손실은 웨이브마다 초기화됩니다.",
                    Map.of("healthLossRatio", 0.15, "cooldownTicks", 20.0)),
            card("J25-S", "pet_towers", "s", "집 밖도 좋아", SILVER,
                    "주인의 마당 범위가 {yardRadius}칸으로 증가합니다.",
                    Map.of("yardRadius", 2.0)),
            card("J25-G1", "pet_towers", "g1", "우리 동네 대장", GOLD,
                    "지정 도구로 내 반려 한 마리를 대장으로 정합니다. 대장의 기본 공격이 {hitsRequired}번 적중하면 같은 마당의 다른 종이 함께 공격합니다. 종마다 한 마리, 최대 {maxAllies}마리가 같은 적에게 기본 공격 피해의 {damageRatio:percent}로 추가 공격합니다.",
                    Map.of("hitsRequired", 3.0, "maxAllies", 2.0, "damageRatio", 1.0)),
            card("J25-G2", "pet_towers", "g2", "다 컸네, 다 컸어", GOLD,
                    "어린 개와 고양이가 성체 전투 능력을 즉시 사용합니다. 새는 공격으로 자기 자신과 같은 마당의 다친 다른 반려 {healTargets}마리를 함께 회복합니다. 실제 성장과 승급에 필요한 유대는 유지합니다.",
                    Map.of("healTargets", 1.0)),
            card("J25-P", "pet_towers", "p", "우리 가족", PRISMATIC,
                    "같은 마당에 실제 성체 개, 고양이, 새가 있으면 고양이 여러 마리도 독립 효과가 발동합니다. 고양이와 새도 개 무리에 참여해 같은 티어 개의 무리 강화 효과를 받으며, 새가 다친 반려 최대 {healTargets}마리를 동시에 회복합니다.",
                    Map.of("healTargets", 3.0)),
            card("J26-S", "developer_towers", "s", "버그 복사기", SILVER,
                    "라운드 첫 조건부 피해 강화 버그가 생기면, 같은 버그나 복사 효과가 없는 가장 가까운 내 개발자 전투 타워 한 기도 그 강화 효과를 {bonusRatio:percent}로 획득합니다. 버그의 불이익은 복사하지 않습니다.",
                    Map.of("bonusRatio", 0.5)),
            card("J26-G1", "developer_towers", "g1", "의도된 사항입니다", GOLD,
                    "경계 조건·버퍼 오버런·하드코딩·은신·지연 로딩의 추가 피해가 조건 없이 발동합니다. 기존 불이익은 유지합니다.",
                    Map.of()),
            card("J26-G2", "developer_towers", "g2", "슈퍼핫픽스", GOLD,
                    "라운드 첫 성공한 핫픽스의 능력치 증가량이 {statMultiplier}배가 되고 불안정을 추가하지 않습니다. 기존 버그 발생은 유지합니다.",
                    Map.of("statMultiplier", 3.0)),
            card("J26-P", "developer_towers", "p", "일괄 배포", PRISMATIC,
                    "라운드 첫 성공한 정식 패치를 현재 보유한 내 모든 개발자 전투 타워에 예약합니다. 패치 횟수는 한 번만 소모하며, 버전 고정과 롤백 실패의 기존 패치 제한은 유지합니다.",
                    Map.of()),
            card("J27-S", "frost", "s", "빙판길", SILVER,
                    "냉매 상태의 적이 죽으면 반경 {radius}블록에 {durationTicks:seconds}초간 빙판을 만듭니다. 빙판 위 적의 이동 속도가 {slow:percent} 감소합니다.",
                    Map.of("radius", 2.0, "durationTicks", 80.0, "slow", 0.3)),
            card("J27-G1", "frost", "g1", "급속 냉동", GOLD,
                    "내 냉기 방출 계열 파동의 한기 부여량이 {chillMultiplier}배가 됩니다. 아군과 적 모두에게 적용합니다.",
                    Map.of("chillMultiplier", 2.0)),
            card("J27-G2", "frost", "g2", "해동 맛집", GOLD,
                    "적을 해동하면 대상 반경 {radius}블록의 최대 {maxTargets}기에게 해동한 타워 공격력의 {damageRatio:percent} 추가 마법 피해를 줍니다. 같은 적을 중심으로 {cooldownTicks:seconds}초마다 발동합니다.",
                    Map.of("radius", 3.0, "maxTargets", 12.0, "damageRatio", 3.0, "cooldownTicks", 60.0)),
            card("J27-P", "frost", "p", "빙하기", PRISMATIC,
                    "내 타워가 만든 냉매 적 최대 {maxSources}기가 {intervalTicks:seconds}초마다 반경 {radius}블록의 다른 적 최대 {maxTargets}기에게 한기 {chill:percent}를 전파합니다. 내 타워가 냉매로 만든 적은 {stunTicks:seconds}초 기절합니다. 같은 적의 기절은 {stunCooldownTicks:seconds}초마다 발동합니다.",
                    Map.of("maxSources", 3.0, "intervalTicks", 40.0, "radius", 3.0, "maxTargets", 8.0, "chill", 0.25, "stunTicks", 40.0, "stunCooldownTicks", 160.0)),
            card("J28-S", "pirate", "s", "약탈의 대가", SILVER,
                    "라운드 첫 보물상자 만기 개봉 시 기본 보물상자 무료 설치권을 1장 얻습니다. 최대 1장 보관합니다.",
                    Map.of()),
            card("J28-G1", "pirate", "g1", "열쇠공", GOLD,
                    "보물상자 만기 개봉 보상이 {rewardBonus:percent} 증가합니다. 라운드 첫 만기 개봉 시 남은 내 보물상자가 {roundReduction}라운드 일찍 열립니다. 기본 환급, 영구 성장, 뱃사공 수입은 유지하며 연쇄 개봉도 건별로 한 번씩 정산합니다.",
                    Map.of("rewardBonus", 0.5, "roundReduction", 1.0)),
            card("J28-G2", "pirate", "g2", "함대 포격", GOLD,
                    "내 제독·항해사 계열은 매 전투 첫 {openingAttacks}회 기본 공격마다 {shotSpacingTicks:seconds}초 간격으로 포탄을 {extraShots}발 추가 발사합니다. 포탄은 대상 반경 {radius}블록의 최대 {maxTargets}기에게 공격력의 {damageRatio:percent} 물리 피해를 줍니다. 대상이 죽거나 사거리 밖으로 나가면 사거리 안에서 다시 선택합니다.",
                    Map.of("openingAttacks", 5.0, "extraShots", 2.0, "shotSpacingTicks", 4.0, "radius", 2.5, "maxTargets", 12.0, "damageRatio", 0.8)),
            card("J28-P", "pirate", "p", "거함 거포", PRISMATIC,
                    "보물상자 만기 개봉 {chestsPerStack}회마다 {diamondReward}다이아와 함포 1중첩을 얻습니다. 즉시 함포 {initialStacks}중첩을 얻습니다. 전투 시작에 함포 1중첩을 소모하고 가장 강한 내 원본 공격 타워의 현재 공격력을 고정합니다. {intervalTicks:seconds}초마다 총 {shots}회 전방 적을 다시 골라 반경 {radius}블록의 최대 {maxTargets}기에게 고정 공격력의 {damageRatio:percent} 물리 피해를 줍니다. 전투 종료 시 남은 포격은 취소합니다.",
                    Map.of("chestsPerStack", 3.0, "diamondReward", 100.0, "initialStacks", 1.0, "intervalTicks", 40.0, "shots", 5.0, "radius", 3.0, "maxTargets", 12.0, "damageRatio", 1.6)),
            card("J29-S", "mage_towers", "s", "막타 환급", SILVER,
                    "공격 주문으로 적을 처치하면 그 주문에 실제 사용한 마나의 {refundRatio:percent}를 돌려받습니다. 주문당 1회.",
                    Map.of("refundRatio", 0.2)),
            card("J29-G1", "mage_towers", "g1", "마나 홍수", GOLD,
                    "즉시 마나 {initialMana}을 얻습니다. 자연 마나 생산량이 {productionMultiplier}배가 되며, 주문을 쓴 마법사도 자연 마나 생산에 참여합니다.",
                    Map.of("initialMana", 300.0, "productionMultiplier", 2.0)),
            card("J29-G2", "mage_towers", "g2", "이중 주문", GOLD,
                    "마법사마다 {castInterval}번째 공격 주문은 피해를 {damageRatio:percent}로 한 번 더 적용합니다. 추가 피해에는 마나 소모가 없습니다.",
                    Map.of("castInterval", 3.0, "damageRatio", 0.6)),
            card("J29-P", "mage_towers", "p", "온 세상이 사거리", PRISMATIC,
                    "마나 {manaCost} 이상에서 쓰는 일반 공격 주문은 레인 전체의 적 최대 {maxTargets}기에 피해를 적용하며, 주문당 마나 {manaCost}을 소모합니다. 차원 붕괴는 제외합니다.",
                    Map.of("manaCost", 300.0, "maxTargets", 20.0)),
            card("J30-S", "insect_towers", "s", "알껍질 방패", SILVER,
                    "부활한 벌레가 처음 받는 피해 1회를 막습니다.",
                    Map.of()),
            card("J30-G1", "insect_towers", "g1", "급행 부화", GOLD,
                    "벌레마다 첫 {revivalCount}번의 부활 대기시간이 {waitReduction:percent} 감소합니다. 이때 부활하면 반경 {radius}블록 안에서 부활을 기다리는 다른 벌레 최대 {maxNeighbors}기의 남은 대기시간이 {neighborReductionTicks:seconds}초 감소합니다.",
                    Map.of("revivalCount", 3.0, "waitReduction", 0.5, "radius", 6.0, "maxNeighbors", 2.0, "neighborReductionTicks", 40.0)),
            card("J30-G2", "insect_towers", "g2", "군락 대행진", GOLD,
                    "원본 벌레가 처음 죽으면 최대 체력과 공격력이 원본의 {statRatio:percent}인 유충 {spawnCount}기를 생성합니다. 예약을 포함해 플레이어당 매 라운드 최대 {roundCap}기입니다. 유충은 사망·접촉 폭발을 계승하며 유충 생성·부활·부활 거점은 계승하지 않습니다.",
                    Map.of("statRatio", 0.4, "spawnCount", 2.0, "roundCap", 6.0)),
            card("J30-P", "insect_towers", "p", "살아 있는 군락", PRISMATIC,
                    "살아 있는 내 원본 벌레도 부활 거점이 됩니다. 원래 스포너가 사라져도 기존 스포너 연결 범위 안의 동료 원본 벌레 곁에서 부활할 수 있습니다.",
                    Map.of()),
            card("J31-S", "future_agency_towers", "s", "교차 사격", SILVER,
                    "원본 요원과 그 연결 생존자가 {windowTicks:seconds}초 안에 같은 적을 공격하면 {durationTicks:seconds}초 속박합니다. 같은 원본의 생존자들은 대상별 {cooldownTicks:seconds}초 재사용 대기시간을 공유합니다.",
                    Map.of("windowTicks", 40.0, "durationTicks", 40.0, "cooldownTicks", 160.0)),
            card("J31-G1", "future_agency_towers", "g1", "살아서 돌아왔다", GOLD,
                    "다음 웨이브에 참가하는 연결 생존자는 체력을 모두 회복합니다. 첫 {durationTicks:seconds}초 동안 사거리가 레인 전체로 늘고 공격력이 {damageBonus:percent} 증가합니다.",
                    Map.of("durationTicks", 120.0, "damageBonus", 0.6)),
            card("J31-G2", "future_agency_towers", "g2", "구조대 증원", GOLD,
                    "원본 요원 한 기가 유지할 수 있는 연결 생존자가 {survivorCap}기로 늘어납니다. 원본과 연결 생존자가 함께 살아 있으면 원본이 받는 피해가 {damageReduction:percent} 감소합니다.",
                    Map.of("survivorCap", 2.0, "damageReduction", 0.25)),
            card("J31-P", "future_agency_towers", "p", "구조 타임루프", PRISMATIC,
                    "원본 요원이 처음 죽을 피해를 받으면 자신과 연결 생존자를 웨이브 시작 체력으로 복원합니다. 이번 웨이브에 죽은 연결 생존자도 복귀합니다. 원본마다 라운드당 1회이며 생존자를 추가 생성하거나 성장·시작 효과를 다시 발동하지 않습니다.",
                    Map.of())
    );

    private JobAugmentCatalog() {}

    static List<Entry> entries() {
        return ENTRIES;
    }

    static List<AugmentDefinition> definitions() {
        return ENTRIES.stream().map(Entry::definition).toList();
    }

    private static Entry card(String reviewId, String job, String suffix, String name, AugmentRarity rarity,
                              String description, Map<String, Double> parameters) {
        String id = "job_" + job + "_" + suffix;
        String registeredJob = switch (job) {
            case "atlantis_towers" -> "atlantis";
            case "developer_towers" -> "developer";
            case "gamble" -> "gamble_towers";
            default -> job;
        };
        return new Entry(reviewId, new AugmentDefinition(id, name, rarity, AugmentCategory.GENERAL,
                id, false, false, false, false, Set.of(5, 15, 25), Set.of(), description, "semion-td:" + registeredJob),
                parameters);
    }
}
