package kim.biryeong.semiontd.effect;

public enum TimedEffectType {
    TOWER_ATTACK_SPEED_REDUCTION,
    TOWER_RANGE_REDUCTION,
    TOWER_DAMAGE_BONUS,
    TOWER_ATTACK_SPEED_BONUS,
    TOWER_RANGE_BONUS,
    TOWER_DAMAGE_REDUCTION,
    TOWER_MAX_HEALTH_BONUS,
    TOWER_INCOME_DAMAGE_BONUS,
    TOWER_WAVE_DAMAGE_BONUS,
    TOWER_HEAL_AMOUNT_BONUS,
    TOWER_ABILITY_INTERVAL_REDUCTION,
    MONSTER_DAMAGE_REDUCTION,
    MONSTER_TOWER_DAMAGE_TAKEN_BONUS,
    MONSTER_MOVE_SPEED_BONUS,
    MONSTER_MOVE_SPEED_REDUCTION,
    MONSTER_ATTACK_DAMAGE_BONUS,
    MONSTER_ATTACK_DAMAGE_REDUCTION,
    MONSTER_ATTACK_SPEED_BONUS,
    MONSTER_ATTACK_SPEED_REDUCTION
}
