package kim.biryeong.semiontd.game;

public enum TeamMoneyTransferResultType {
    SUCCESS,
    DISABLED,
    INVALID_AMOUNT,
    PLAYER_NOT_IN_GAME,
    TEAM_NOT_ACTIVE,
    NOT_TEAMMATE,
    SELF_TRANSFER,
    RECEIVE_COOLDOWN_ACTIVE,
    AMOUNT_EXCEEDS_ROUND_LIMIT,
    REQUEST_NOT_FOUND,
    REQUEST_ALREADY_OPEN,
    REQUEST_EXPIRED,
    REQUESTER_NO_LONGER_ELIGIBLE,
    MATCH_ENDED,
    NOT_ENOUGH_DIAMOND
}
