package kim.biryeong.semiontd.game;

public enum TowerUpgradeResult {
    SUCCESS,
    INVALID_PHASE,
    PLAYER_NOT_IN_GAME,
    PLAYER_TEAM_ELIMINATED,
    UNKNOWN_LANE,
    NO_TOWER_AT_POSITION,
    TOWER_NOT_OWNED,
    TOWER_NOT_UPGRADABLE,
    UNKNOWN_UPGRADE,
    UNKNOWN_TARGET_TYPE,
    TOWER_NOT_ALLOWED,
    NOT_ENOUGH_MINERAL,
    NOT_ENOUGH_ADV_EXPERIENCE
}
