package kim.biryeong.semionTd.game;

public enum TowerUpgradeResult {
    SUCCESS,
    INVALID_PHASE,
    PLAYER_NOT_IN_GAME,
    PLAYER_TEAM_ELIMINATED,
    UNKNOWN_LANE,
    NO_TOWER_AT_POSITION,
    TOWER_NOT_UPGRADABLE,
    UNKNOWN_UPGRADE,
    UNKNOWN_TARGET_TYPE,
    NOT_ENOUGH_MINERAL
}
